services:
  - type: web
    name: smart-supply
    env: docker
    plan: free
    region: oregon
    buildCommand: docker build -t smart-supply .
    # startCommand not needed, uses Dockerfile ENTRYPOINT
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      # Database settings (Manual input for Supabase)
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "6543"
      - key: DB_DATABASE
        value: "postgres"
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

# Database section removed to use external Supabase DB
